FROM node:16-alpine as build

WORKDIR /app

COPY package.json /app

RUN npm install --location=global npm@8.15.0
RUN npm install

COPY . /app

RUN npm run build

FROM nginx:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/production /usr/share/nginx/html